apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.role.name }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.roleBinding.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.role.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.roleBinding.serviceAccountName }}
  namespace: {{ .Values.rbac.roleBinding.namespace }}
